### ISSUE TITLE
Broken Texture

### ISSUE THREAD

**Issue by Gh0stic45** [al132/ATM-Illumination#1]
I don't know if it's from the pack configs or the Harder Ores mod, but the texture for sugar that you receive after it goes through the sifter is broken. The tooltip still shows that it's Minecraft sugar just the icon is broken.

**Comment by al132** [comment]
I haven't checked yet, but this should be fixed now in the most recent pack version 
https://github.com/Draco18s/ReasonableRealism/issues/9
